name: build-cipherblue
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Cipherblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - cipherblue.yml
          #- ciphercore.yml
    steps:
      - name: Build Cipherblue
        uses: blue-build/github-action@main
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: false
          squash: true
